### ISSUE TITLE
SKU not valid anymore

### ISSUE THREAD

**Issue by Jeoff-Sopheon** [barracudanetworks/waf-azure-templates#3]
Error when deploying template:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"BadRequest\",\r\n \"message\": \"The object supplied in the request is invalid\",\r\n \"target\": \"sku.name\"\r\n }\r\n}"}]}

I fixed it by manually editing the template.
I changed one of the pricingTier variables to 'standalone'

As per Microsoft's article:

If you might have some subscriptions in the pre-April 2018 pricing model, you can specify the Standalone pricing tier, and this will succeed for both subscription in the pre-April 2018 pricing model and for subscriptions in the new pricing. For workspaces in subscriptions that have adopted the new proicing model, the pricing tier will be set to PerGB2018.

**Comment by barracudanetworks-waf** [comment]
This should be resolved with the new templates that are uploaded now.
